export const t = {
  home: "首页",
  itinerary: "行程",
  travelers: "同行",
  day: "第",
  dayUnit: "天",
  activities: "行程",
  mustDo: "想去",
  niceToDo: "随兴",
  bookings: "预订",
  booked: "已预订",
  openInAppleMaps: "Apple 地图",
  openInGoogleMaps: "Google 地图",
  openInAmap: "高德地图",
  signatureDishes: "招牌",
  placeKind: {
    restaurant: "餐厅",
    sight: "景点",
    shrine: "神社/寺庙",
    shop: "购物",
    hotel: "酒店",
    station: "车站",
    other: "其他",
  },
  bookingKind: {
    flight: "航班",
    hotel: "住宿",
    shinkansen: "新干线",
    other: "其他",
  },
  countdown: {
    label: "距离出发",
    days: "天",
    hours: "时",
    minutes: "分",
    seconds: "秒",
    inProgress: "旅途中",
    ended: "旅程已结束",
  },
} as const;
